

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aws-free-data.cvkmnqgpbmdr.ap-northeast-2.rds.amazonaws.com:3306/youquiz
    username: root
    password: da7879!!!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false #true
    properties:
      hibernate:
        format_sql: false #true
        dialect: org.hibernate.dialect.MySQL8Dialect
